name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:resolute
    steps:
      - name: Install requirements
        run: |
          apt-get -y update
          apt-get -y install build-essential curl libssl-dev git \
            libgtk-4-dev libadwaita-1-dev libwebkitgtk-6.0-dev libmpv-dev gettext nodejs flatpak-builder python3-aiohttp python3-tomlkit
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y \
            org.gnome.Sdk//50 \
            org.gnome.Platform//50 \
            org.freedesktop.Sdk.Extension.rust-stable//25.08 \
            org.freedesktop.Platform.ffmpeg-full//24.08 \
            org.freedesktop.Platform.VAAPI.Intel//25.08

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Update git submodules
        run: git submodule update --init --recursive

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
  
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build flatpak package
        run: ./flatpak/build.sh
      - name: Upload flatpak package to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./flatpak/*.flatpak